locale_ids = {'afrikaans - south africa': '0436',
              'afrikaans': '0436',
              'albanian - albania': '041c',
              'alsatian': '0484',
              'amharic - ethiopia': '045e',
              'arabic - algeria': '1401',
              'arabic - bahrain': '3c01',
              'arabic - egypt': '0c01',
              'arabic - iraq': '0801',
              'arabic - jordan': '2c01',
              'arabic - kuwait': '3401',
              'arabic - lebanon': '3001',
              'arabic - libya': '1001',
              'arabic - morocco': '1801',
              'arabic - oman': '2001',
              'arabic - qatar': '4001',
              'arabic - saudi arabia': '0401',
              'arabic': '0401',
              'arabic - syria': '2801',
              'arabic - tunisia': '1c01',
              'arabic - u.a.e.': '3801',
              'arabic - united arabic emirates': '3801',
              'arabic - yemen': '2401',
              'armenian - armenia': '042b',
              'assamese': '044d',
              'azeri (cyrillic)': '082c',
              'azeri (latin)': '042c',
              'bashkir': '046d',
              'basque': '042d',
              'belarusian': '0423',
              'bengali (bangladesh)': '0845',
              'bengali (india)': '0445',
              'bosnian (bosnia/herzegovina)': '141a',
              'breton': '047e',
              'bulgarian': '0402',
              'burmese': '0455',
              'catalan': '0403',
              'cherokee - united states': '045c',
              'chinese - hong kong sar': '0c04',
              'chinese - macao sar': '1404',
              "chinese - people's republic of china": '0804',
              'chinese': '0804',
              'chinese - singapore': '1004',
              'chinese - taiwan': '0404',
              'corsican': '0483',
              'croatian': '041a',
              'croatian (bosnia/herzegovina)': '101a',
              'czech': '0405',
              'danish': '0406',
              'dari': '048c',
              'divehi': '0465',
              'dutch - belgium': '0813',
              'dutch - netherlands': '0413',
              'dutch': '0413',
              'edo': '0466',
              'english - australia': '0c09',
              'english - belize': '2809',
              'english - canada': '1009',
              'english - caribbean': '2409',
              'english - hong kong sar': '3c09',
              'english - india': '4009',
              'english - indonesia': '3809',
              'english - ireland': '1809',
              'english - jamaica': '2009',
              'english - malaysia': '4409',
              'english - new zealand': '1409',
              'english - philippines': '3409',
              'english - singapore': '4809',
              'english - south africa': '1c09',
              'english - trinidad': '2c09',
              'english - united kingdom': '0809',
              'english - united states': '0409',
              'english - us': '0409',
              'english': '0409',
              'english - zimbabwe': '3009',
              'estonian': '0425',
              'fyro macedonian': '042f',
              'faroese': '0438',
              'farsi': '0429',
              'filipino': '0464',
              'finnish': '040b',
              'french - belgium': '080c',
              'french - cameroon': '2c0c',
              'french - canada': '0c0c',
              'french - cote dâ€™ivoire': '300c',
              'french - democratic rep. of congo': '240c',
              'french - france': '040c',
              'french': '040c',
              'french - haiti': '3c0c',
              'french - luxembourg': '140c',
              'french - mali': '340c',
              'french - monaco': '180c',
              'french - morocco': '380c',
              'french - north africa': 'e40c',
              'french - reunion': '200c',
              'french - senegal': '280c',
              'french - switzerland': '100c',
              'french - west indies': '1c0c',
              'frisian - netherlands': '0462',
              'fulfulde - nigeria': '0467',
              'galician': '0456',
              'georgian': '0437',
              'german - austria': '0c07',
              'german - germany': '0407',
              'german': '0407',
              'german - liechtenstein': '1407',
              'german - luxembourg': '1007',
              'german - switzerland': '0807',
              'greek': '0408',
              'greenlandic': '046f',
              'guarani - paraguay': '0474',
              'gujarati': '0447',
              'hid (human interface device)': '04ff',
              'hausa - nigeria': '0468',
              'hawaiian - united states': '0475',
              'hebrew': '040d',
              'hindi': '0439',
              'hungarian': '040e',
              'ibibio - nigeria': '0469',
              'icelandic': '040f',
              'igbo - nigeria': '0470',
              'indonesian': '0421',
              'inuktitut': '045d',
              'irish': '083c',
              'italian - italy': '0410',
              'italian - switzerland': '0810',
              'japanese': '0411',
              'kannada': '044b',
              'kanuri - nigeria': '0471',
              'kashmiri': '0860',
              'kashmiri (arabic)': '0460',
              'kazakh': '043f',
              'khmer': '0453',
              'kinyarwanda': '0487',
              'konkani': '0457',
              'korean': '0412',
              'kyrgyz (cyrillic)': '0440',
              'kâ€™iche': '0486',
              'lao': '0454',
              'latin': '0476',
              'latvian': '0426',
              'lithuanian': '0427',
              'luxembourgish': '046e',
              'malay - brunei darussalam': '083e',
              'malay - malaysia': '043e',
              'malayalam': '044c',
              'maltese': '043a',
              'manipuri': '0458',
              'maori - new zealand': '0481',
              'mapudungun': '0471',
              'marathi': '044e',
              'mohawk': '047c',
              'mongolian (cyrillic)': '0450',
              'mongolian (mongolian)': '0850',
              'nepali': '0461',
              'nepali - india': '0861',
              'norwegian (bokmã¥l)': '0414',
              'norwegian (nynorsk)': '0814',
              'occitan': '0482',
              'oriya': '0448',
              'oromo': '0472',
              'papiamentu': '0479',
              'pashto': '0463',
              'polish': '0415',
              'portuguese - brazil': '0416',
              'portuguese - portugal': '0816',
              'punjabi': '0446',
              'punjabi (pakistan)': '0846',
              'quecha - bolivia': '046b',
              'quecha - ecuador': '086b',
              'quecha - peru': '0c6b',
              'rhaeto-romanic': '0417',
              'romanian': '0418',
              'romanian - moldava': '0818',
              'russian': '0419',
              'russian - moldava': '0819',
              'sami (lappish)': '043b',
              'sanskrit': '044f',
              'scottish gaelic': '043c',
              'sepedi': '046c',
              'serbian (cyrillic)': '0c1a',
              'serbian (latin)': '081a',
              'sindhi - india': '0459',
              'sindhi - pakistan': '0859',
              'sinhalese - sri lanka': '045b',
              'slovak': '041b',
              'slovenian': '0424',
              'somali': '0477',
              'sorbian': '042e',
              'spanish - argentina': '2c0a',
              'spanish - bolivia': '400a',
              'spanish - chile': '340a',
              'spanish - colombia': '240a',
              'spanish - costa rica': '140a',
              'spanish - dominican republic': '1c0a',
              'spanish - ecuador': '300a',
              'spanish - el salvador': '440a',
              'spanish - guatemala': '100a',
              'spanish - honduras': '480a',
              'spanish - latin america': '580a',
              'spanish - mexico': '080a',
              'spanish - nicaragua': '4c0a',
              'spanish - panama': '180a',
              'spanish - paraguay': '3c0a',
              'spanish - peru': '280a',
              'spanish - puerto rico': '500a',
              'spanish - spain (modern sort)': '0c0a',
              'spanish': '0c0a',
              'spanish - spain (traditional sort)': '040a',
              'spanish - united states': '540a',
              'spanish - uruguay': '380a',
              'spanish - venezuela': '200a',
              'sutu': '0430',
              'swahili': '0441',
              'swedish': '041d',
              'swedish - finland': '081d',
              'syriac': '045a',
              'tajik': '0428',
              'tamazight (arabic)': '045f',
              'tamazight (latin)': '085f',
              'tamil': '0449',
              'tatar': '0444',
              'telugu': '044a',
              'thai': '041e',
              'tibetan - bhutan': '0851',
              "tibetan - people's republic of china": '0451',
              'tigrigna - eritrea': '0873',
              'tigrigna - ethiopia': '0473',
              'tsonga': '0431',
              'tswana': '0432',
              'turkish': '041f',
              'turkmen': '0442',
              'uighur - china': '0480',
              'ukrainian': '0422',
              'urdu': '0420',
              'urdu - india': '0820',
              'uzbek (cyrillic)': '0843',
              'uzbek (latin)': '0443',
              'venda': '0433',
              'vietnamese': '042a',
              'welsh': '0452',
              'wolof': '0488',
              'xhosa': '0434',
              'yakut': '0485',
              'yi': '0478',
              'yiddish': '043d',
              'yoruba': '046a',
              'zulu': '0435'}


SC = {"nums":    ['02', '03', '04', '05', '06', '07', '08', '09', '0a', '0b'],
      "top_row": ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19'],
      "homerow": ['1e', '1f', '20', '21', '22', '23', '24', '25', '26', '27'],
      "bot_row": ['2c', '2d', '2e', '2f', '30', '31', '32', '33', '34', '35'],
      "symbols": ['29', '0c', '0d', '1a', '1b', '28', '2b'],
      "iso_key": '56'}


SC_REVERSE = {'02': ('nums', 0),
              '03': ('nums', 1),
              '04': ('nums', 2),
              '05': ('nums', 3),
              '06': ('nums', 4),
              '07': ('nums', 5),
              '08': ('nums', 6),
              '09': ('nums', 7),
              '0a': ('nums', 8),
              '0b': ('nums', 9),
              '0c': ('symbols', 1),
              '0d': ('symbols', 2),
              '10': ('top_row', 0),
              '11': ('top_row', 1),
              '12': ('top_row', 2),
              '13': ('top_row', 3),
              '14': ('top_row', 4),
              '15': ('top_row', 5),
              '16': ('top_row', 6),
              '17': ('top_row', 7),
              '18': ('top_row', 8),
              '19': ('top_row', 9),
              '1a': ('symbols', 3),
              '1b': ('symbols', 4),
              '1e': ('homerow', 0),
              '1f': ('homerow', 1),
              '20': ('homerow', 2),
              '21': ('homerow', 3),
              '22': ('homerow', 4),
              '23': ('homerow', 5),
              '24': ('homerow', 6),
              '25': ('homerow', 7),
              '26': ('homerow', 8),
              '27': ('homerow', 9),
              '28': ('symbols', 5),
              '29': ('symbols', 0),
              '2b': ('symbols', 6),
              '2c': ('bot_row', 0),
              '2d': ('bot_row', 1),
              '2e': ('bot_row', 2),
              '2f': ('bot_row', 3),
              '30': ('bot_row', 4),
              '31': ('bot_row', 5),
              '32': ('bot_row', 6),
              '33': ('bot_row', 7),
              '34': ('bot_row', 8),
              '35': ('bot_row', 9),
              '56': 'iso_key'}


VK = {"'": 'OEM_7',
      ',': 'OEM_COMMA',
      '-': 'OEM_MINUS',
      '.': 'OEM_PERIOD',
      '/': 'OEM_2',
      '0': '0',
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      ';': 'OEM_1',
      '=': 'OEM_PLUS',
      '[': 'OEM_4',
      '\\': 'OEM_5',
      ']': 'OEM_6',
      '`': 'OEM_3',
      'a': 'A',
      'b': 'B',
      'c': 'C',
      'd': 'D',
      'dec_sep': 'DECIMAL',
      'e': 'E',
      'f': 'F',
      'g': 'G',
      'h': 'H',
      'i': 'I',
      'iso_key': 'OEM_102',
      'j': 'J',
      'k': 'K',
      'l': 'L',
      'm': 'M',
      'n': 'N',
      'o': 'O',
      'p': 'P',
      'q': 'Q',
      'r': 'R',
      's': 'S',
      'space': 'SPACE',
      't': 'T',
      'u': 'U',
      'v': 'V',
      'w': 'W',
      'x': 'X',
      'y': 'Y',
      'z': 'Z'}


sym_upper = {'`': '~',
             '[': '{',
             ']': '}',
             '/': '?',
             '=': '+',
             '-': '_',
             '\\': '|',
             "'": '"',
             ',': '<',
             '.': '>',
             ';': ':',
             '1': '!',
             '2': '@',
             '3': '#',
             '4': '$',
             '5': '%',
             '6': '^',
             '7': '&',
             '8': '*',
             '9': '(',
             '0': ')'}


static_text = '\n\n\nKEYNAME\n\n01\tEsc\n0e\tBackspace\n0f\tTab\n1c\tEnter\n1d\tCtrl\n2a\tShift\n36\t"Right Shift"\n37'\
         '\t"Num *"\n38\tAlt\n39\tSpace\n3a\t"Caps Lock"\n3b\tF1\n3c\tF2\n3d\tF3\n3e\tF4\n3f\tF5\n40\tF6\n41\tF7'\
         '\n42\tF8\n43\tF9\n44\tF10\n45\tPause\n46\t"Scroll Lock"\n47\t"Num 7"\n48\t"Num 8"\n49\t"Num 9"\n4a'\
         '\t"Num -"\n4b\t"Num 4"\n4c\t"Num 5"\n4d\t"Num 6"\n4e\t"Num +"\n4f\t"Num 1"\n50\t"Num 2"\n51\t"Num 3"'\
         '\n52\t"Num 0"\n53\t"Num Del"\n54\t"Sys Req"\n57\tF11\n58\tF12\n7c\tF13\n7d\tF14\n7e\tF15\n7f\tF16\n80'\
         '\tF17\n81\tF18\n82\tF19\n83\tF20\n84\tF21\n85\tF22\n86\tF23\n87\tF24\n\nKEYNAME_EXT\n\n1c\t"Num Enter"'\
         '\n1d\t"Right Ctrl"\n35\t"Num /"\n37\t"Prnt Scrn"\n38\t"Right Alt"\n45\t"Num Lock"\n46\tBreak\n47\tHome'\
         '\n48\tUp\n49\t"Page Up"\n4b\tLeft\n4d\tRight\n4f\tEnd\n50\tDown\n51\t"Page Down"\n52\tInsert\n53'\
         '\tDelete\n54\t<00>\n56\tHelp\n5b\t"Left Windows"\n5c\t"Right Windows"\n5d\tApplication\n\n'
